---
resources:
# Manifests and Releases
- name: windows-syslog-release
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/windows-syslog-release.git
    ignore_paths:
    - .final_builds/*
    - releases/*

- name: windows-syslog-release-push
  type: git
  source:
    branch: master
    private_key: ((windows_release_deploy_key))
    uri: git@github.com:cloudfoundry/windows-syslog-release.git

- name: golang-release
  type: git
  source:
    branch: master
    uri: https://github.com/bosh-packages/golang-release.git
    tag_filter: '*'

- name: syslog-ci
  type: git
  source:
    branch: develop
    uri: https://github.com/cloudfoundry/syslog-release.git

# ENV
- name: tycho-env-bbl-state
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/tycho-env.git
    private_key: ((tycho_env_git_deploy_key))
    paths:
    - bbl-state/*
    - bbl-config/*
    - google_account_creds.json
    - operations/*

jobs:
- name: syslog-acceptance-tests
  public: true
  serial: true
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: windows-syslog-release
      trigger: true
    - get: tycho-env-bbl-state
  - task: syslog-acceptance
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
          tag: v5
      run:
        path: bash
        args:
          - -c
          - |
            #!/bin/bash

            set -e

            workspace=$PWD
            mkdir -p $GOPATH/src/github.com/cloudfoundry
            ln -s $workspace/windows-syslog-release $GOPATH/src/github.com/cloudfoundry/windows-syslog-release

            function kill_bbl_ssh {
              pkill ssh || true
            }

            trap kill_bbl_ssh EXIT

            pushd $workspace/tycho-env-bbl-state
              source .envrc
            popd

            pushd $GOPATH/src/github.com/cloudfoundry/windows-syslog-release
              ./scripts/test
            popd
      caches:
      - path: windows-syslog-release/blobs
      inputs:
      - name: windows-syslog-release
      - name: tycho-env-bbl-state

- name: bump-go-package
  public: true
  serial: true
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: golang-release
      trigger: true
    - get: syslog-ci
    - get: windows-syslog-release
  - task: bump-go-package
    file: syslog-ci/.concourse/tasks/bump-release-package/task.yml
    input_mapping:
      release: windows-syslog-release
      package-release: golang-release
    params:
      BLOBS_BUCKET_ACCESS_KEY_ID: ((syslog_release_blobs_buckets_access_key_id))
      BLOBS_BUCKET_SECRET_KEY: ((syslog_release_blobs_buckets_secret_access_key))
      PACKAGE_NAME: golang-1-windows
  - put: windows-syslog-release-push
    params:
      repository: updated-release
