#!/bin/bash

set -euxo pipefail

pushd "$(dirname "$0")/.."
  bosh create-release --force --version="$(date "+%s")"
  bosh upload-release
popd
bosh upload-stemcell https://bosh.io/d/stemcells/bosh-google-kvm-windows2019-go_agent
bosh upload-release https://bosh.io/d/github.com/cloudfoundry/syslog-release
bosh upload-release https://bosh.io/d/github.com/cloudfoundry-incubator/windows-utilities-release

pushd "$(dirname "$0")/../tests"
  go install github.com/onsi/ginkgo/v2/ginkgo@latest
  ginkgo -r --procs=2 "$@"
popd
